### ISSUE TITLE
CUDA error/SVD not converging

### ISSUE THREAD

**Issue by zgojcic** [WangYueFt/prnet#8]
Dear authors, 

thank you for making the code public. I have tried to run your method on our own data (partial point clouds of the ShapeNet cars) and have stumbled on a CUDA error as already mentioned in [a previous issue](https://github.com/WangYueFt/prnet/issues/2).

We have tried following things to mitigate the error:

1) As mentioned in one of the issues we have tried replacing top-k with sort().
2) We have tried to improve the conditioning of the ill-contioned covariance-matrices by adding small constant values to the diagonal.
3) Running the SVD on the GPU instead of the CPU. 
4) Using a newer version of pytorch (1.5). In this case there was no CUDA error did not occur but the SVD did not converge "SBDSC did not converged error"

We are wondering if you maybe have some other suggestions or know what could be done to alleviate this problem. Do you know hot other people managed to solve this issues?

Thanks for your help 

Zan

**Comment by SebastianGrans** [comment]
I've also struggled with these issues. I don't remember exactly how I solved it, but the current state of my fork runs without these issues. [Link](https://github.com/SebastianGrans/prnet)

**Comment by yangninghua** [comment]
```

Traceback (most recent call last):
  File "/home/boyun/deepglint/code/ICP/prnet_oricode/main.py", line 177, in <module>
    main()
  File "/home/boyun/deepglint/code/ICP/prnet_oricode/main.py", line 171, in main
    train(args, net, train_loader, test_loader)
  File "/home/boyun/deepglint/code/ICP/prnet_oricode/main.py", line 49, in train
    info_train = net._train_one_epoch(epoch=epoch, train_loader=train_loader, opt=opt)
  File "/media/boyun/NO_1/ubuntu16.04/deepglint/code/ICP/prnet_oricode/model.py", line 705, in _train_one_epoch
    opt)
  File "/media/boyun/NO_1/ubuntu16.04/deepglint/code/ICP/prnet_oricode/model.py", line 624, in _train_one_batch
    feature_disparity = self.forward(src, tgt)
  File "/media/boyun/NO_1/ubuntu16.04/deepglint/code/ICP/prnet_oricode/model.py", line 590, in forward
    rotation_ab, translation_ab, rotation_ba, translation_ba, feature_disparity = self.acpnet(*input)
  File "/home/boyun/.conda/envs/py3_6--pytorch1_0_1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/boyun/NO_1/ubuntu16.04/deepglint/code/ICP/prnet_oricode/model.py", line 540, in forward
    rotation_ab, translation_ab = self.head(src_embedding, tgt_embedding, src, tgt, temperature)
  File "/home/boyun/.conda/envs/py3_6--pytorch1_0_1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/boyun/NO_1/ubuntu16.04/deepglint/code/ICP/prnet_oricode/model.py", line 453, in forward
    H = torch.matmul(src_centered, src_corr_centered.transpose(2, 1).contiguous()).cpu()
RuntimeError: CUDA error: device-side assert triggered

```

**Comment by Dengzhi-USTC** [comment]
May be your data will generate nan?

**Comment by alejandroHdzV** [comment]
I am currently facing this error, does any one know how to fix it? Thanks in advance.

Error: 'torch._C._LinAlgError: linalg.svd: The algorithm failed to converge because the input matrix is ill-conditioned or has too many repeated singular values (error code: 2).'
